### ISSUE TITLE
Details on radiance caching

### ISSUE THREAD

**Issue by ShilinC** [Tom94/practical-path-guiding#13]
Hi Thomas,

I looked at the code and there is one part that I don't quite understand:
In DTreeWrapper's record function:
Float irradiance = rec.radiance / rec.woPdf;

Based on my understanding you recorded this "irradiance" into the dTree. Why not directly record rec.radiance? I tried but looks like if I record the rec.radiance, then the result will have a lot more noise. And I'm a bit confused here. Based on the definitions, shouldn't the incoming irradiance and radiance be related by a cosine term? Why are they related by this woPdf?
![irradiance](https://user-images.githubusercontent.com/11979931/86705044-4f1fbb00-bfca-11ea-8337-9a1eb276cb8c.png)

Thanks!!!

**Comment by Tom94** [comment]
Hi Shilin,

intuitively speaking, our ultimate goal is to sample each quad of the DTree proportional to the incident "energy" that flows through it. So we want to store said "energy" within each quad. What I mean by "energy" is the integral of radiance over the quad's solid-angle footprint. This is where `woPdf` comes in: we estimate that integral via Monte Carlo and `woPdf` is the solid-angle PDF we use for importance sampling.

You raise a good point on whether the units of this integral truly are "irradiance"---this is actually a slight abuse of notation and the cosine factor is indeed missing. The integral has units of flux per _projected_ surface area as opposed to Wikipedia's definition of irradiance as flux per _un_projected surface area. Hence the discrepancy of the cosine factor (to convert between projected and unprojected area). In the code, _projected_ area fits better into the framework of radiance, as it makes converting back to radiance easy: assuming piecewise-constant radiance across quads allows dividing each quad's energy by the quad's solid-angle footprint to obtain the learned radiance.

Lastly: irradiance and radiance are not only related by a cosine factor. They're related by an integral _and_ a cosine factor. If you combine your formulas, you get `dE / dw_i == L_i * dot(w_i, n)`. Integrate on both sides to get `E == int(L_i * dot(w_i, n) dw_i)`.
 `woPdf` takes care of the integral and I omit the cosine factor as mentioned above, because energy per projected area is more convenient than energy per area. :)

Cheers!

**Comment by ShilinC** [comment]
Thanks for your quick response! Very nice explanation.
