### ISSUE TITLE
Reason for dropping the previous tree

### ISSUE THREAD

**Issue by ShilinC** [Tom94/practical-path-guiding#14]
Hi Thomas,

Sorry to open another issue... 

I can see you keep two SD-Trees, one for guiding and one for irradiance deposit. If I understand the code correctly, after each iteration you drop the previous tree and build a new tree using the new samples from this new iteration. I guess this is because after you subdivide the tree, leaf nodes are smaller so previously learned sampling maps are not accurate anymore. But do you really need to drop the entire tree? I think the previously learned sampling map still contains a lot of useful information & valid samples and if you drop them completely, then you need to trace them again in the next iteration, which may introduce some redundancy here since some paths may be traced repeatedly. Is there any way to gradually evolve the sampling map so they can adapt to smaller leaves faster without starting from scratch (empty tree)?

Thanks!

**Comment by Tom94** [comment]
Hi Shilin,

no problem at all!

Absolutely: dropping the previous tree is creating a certain level of redundancy. However, due to the power-of-2 sample count scheme, only at most half of all samples are thrown away. So the maximum amount of information you can save by re-using old trees is 2x.

One possible option would be an exponential moving average (e.g. as used by [Dahm and Keller [2018]](https://www.researchgate.net/publication/326168623_Learning_Light_Transport_the_Reinforced_Way)), but exponential moving averages also have downsides. For one, they always emphasize the latest samples, exaggerating their variance. Plus, from my experience, it was difficult to accurately shape the re-use of previous information vs. the use of new information.

In any case, it's an interesting open problem!

**Comment by ShilinC** [comment]
Thanks! Very appreciated!
