### ISSUE TITLE
Binary tree vs Octree

### ISSUE THREAD

**Issue by ShilinC** [Tom94/practical-path-guiding#15]
Hi Thomas,

I'm wondering is there any specific reasons that you choose binary tree over Octree as the spatial representation? I'm not sure but maybe the spatial adaptation can be learned faster if using Octree? I saw that in the paper you mentioned that "Effectively, our threshold ensures that the total number of leaf nodes and the amount of samples in each leaf both grow at the same rate across iterations." I don't know if similar statement can be applied to Octree instead of binary tree. I would like to try Octree but I'm not sure how to set up the SPP and threshold correctly so that this property still hold (maybe change base 2 to base 8?). Please correct me if I'm wrong. If you had tried that, maybe you could share some experience with me?

Thanks!!!

Best,
Shilin

**Comment by Tom94** [comment]
Hi Shilin,

using a base of 8 for the octree would indeed match the overall subdivision behavior of the binary tree. However, the subdivision is more granular with the binary tree than with an octree. (All possible octrees can be represented by a binary tree, but the reverse isn't true.)

Such granular subdivision is desired due to the spp-doubling every iteration. Let's imagine for simplicity that the samples within a leaf node are distributed uniformly in space. Then, after a binary subdivision of that node as well as an spp-doubling step, each new leaf node still gets the same total number of samples. I.e. the quadtree in each leaf node will have a similar noise level compared to the previous iteration. If you did a sudden 8-fold octree subdivision instead, then each new leaf node would receive 4x fewer samples than before until the spp-doubling of later iterations catches up. This problem would manifest as variations in the guiding quality across iterations.

But while octrees exacerbate the above mentioned problem, there is actually another kind of binary tree that ameliorates it! I believe Sebastian Herholz et al. used that new binary tree first (in their 2019 volume guiding paper), but I can't find a concrete description of the data structure while glancing over the paper right now. We might have talked about it in person or in a chatroom. Basically, the (above) assumption of spatially uniform samples can be quite wrong. Thus, it's benefitial to subdivide the binary tree along the axis of largest spatial variation (as opposed to round-robin) at the median sample location (as opposed to the middle of the node). I think implementing that subdivision scheme would be an easy surefire way to improve PPG. :)

Cheers!

**Comment by ShilinC** [comment]
Thanks for the great explanation! 

Yes, I thought that if octree is used then it looks like we have to increase the SPP by 8 times after iteration, i.e., 1, 8, 64, 512, ... so to make sure each leaf receives similar amount of samples. But I'm not sure if it's better or worse than the current binary tree. My original thinking was that octree can be wider and shallower than the binary tree, and each leaf is entirely cubical so aspect ratio looks better (may have better spatial locality when depositing samples, and kd-tree can sometimes result in high aspect ratio cells).

Sorry, one last question: if binary tree is more granular, what motivates you to use quadtree instead of binary tree in the directional space? Actually that's why I thought about using spatial octree because I saw the quadtree is used. 

Thanks!!!

**Comment by Tom94** [comment]
The good thing about the kD-tree subdivision heuristic I mentioned above is that it'll only lead to high aspect-ratio cells if the underlying distribution of samples follows the same high aspect ratio. So I don't think it's a problem in practice.

Regarding the use of the quadtree rather than a binary tree: since the subdivision scheme for the quadtree results in a roughly constant number of cells anyway, the spp-doubling concerns fall away. You raise a good point regarding better granularity of a binary tree, though. I think binary trees (and kD-trees, or even more sophisticated trees) could absolutely result in more accurate directional distributions. The ultimate question will be whether the performance trade-off is worth it. I know no useful experimental results on that end, though. Needs to be investigated. :)

**Comment by ShilinC** [comment]
Yeah, that makes sense. Thanks!
