### ISSUE TITLE
Adjoint Russian Roulette

### ISSUE THREAD

**Issue by iRath96** [Tom94/practical-path-guiding#3]
Hello!
First of all: thank you for the great paper and for sharing this implementation.

However, your implementation of _Adjoint Russian Roulette_ seems to contain a bug:
https://github.com/Tom94/practical-path-guiding/blob/60584511c582144b1bb62323c43ba64832f3fcdb/mitsuba/src/integrators/path/guided_path.cpp#L1878-L1880

From my understanding, this should read `successProb = tMax / wMin`.
In its current form, `successProb` is always greater than `1`, which essentially disables RR.

**Comment by Tom94** [comment]
Hi Alex, absolutely no problem; I believe open source is how research should be done if in any way possible. :)

Thank you for pointing out the bug. To my shame I must admit that several other people already privately pointed it out and I never got around to addressing it. I am a little bit hesitant to simply fix it, because the results from the paper were also generated with this buggy implementation of ADRR (i.e. no RR at all). Fixing the bug would therefore likely improve the results, which would violate reproducibility, even though it would make PPG look better.

I currently have a WIP branch with a bunch of improvements (imported in part from the theory of [Neural Importance Sampling](http://tom94.local/data/publications/mueller18neural/mueller18neural-v3.pdf)) where I will most likely simply remove the buggy ADRR implementation and turn off RR explicitly.

Cheers!

**Comment by iRath96** [comment]
Got it, thanks for letting me know! 👍
